### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by ihrwein** [balabit/syslog-ng#821]
This is just a meta issue for tracking several OSX related issues:
- [x] #805 lib/logmsg.c weak alias error breaks build of 3.7.2 on OS X 10.11
- [x] #806 Absence of clock_gettime() on OS X breaks build of lib/timeutils.c on 3.7.2
- [x] #807 Duplicate symbols (_TLSSslOptions and _last_parser) break build of syslog-ng 3.7.2 on OS X
- [x] #808 OS X ld does not support --whole-archive option, thus breaking the build of 3.7.2 on OS X

Additional TODOs collected by @gregory094:
- [x] **glibtool vs. libtool**: on Darwin based systems glibtool is used instead of libtool. We should handle this difference in `autogen.sh`. Both platforms respect the `LIBTOOL` variable so we should read the proper tool from that environmental variable.
- [x] **bison**: the default `bison` version provided by _Apple Developer Tools_ is `2.3` that doesn't support the `-W` option (`>=3.0`) that we use. That's why the user should install `bison 3.4` using `brew` and set the `YACC` environmental variable to `/usr/local/Cellular/bison/bin/bison` or use `brew link bison` in order to make it the default.
- [x] **configure --with-java**: we use `find` while configuring java... that's bad. The `find` tool in _OSX_ is little bit different from _UNIX-like-find_. It has a different interface and options.
- [x] **configure --with-amqp**:  this is an _openssl_ related issue and not our fault. After `OSX 10.11 El Capitan` Apple removed `/usr/include/` that's why we get an error in configuration time. We should set `--with-opt-dir=/usr/local/Cellular/openssl/include` or use `brew link openssl` to avoid this.
- [ ] **ivykis**: I've already mentioned that `ivykis` has some problems dealing with _non-case-sensitive filesystems_ because its structure contains files with the same name. We should patch `ivykis` or fork it and build _OS X_ support with that.

**Comment by bkil-syslogng** [comment]
Possibly related abandoned feature branch in an attempt to add support: https://github.com/balabit/syslog-ng/compare/master...gregory094:3.6/f/macosx

**Comment by bkil-syslogng** [comment]
It would be best if we had a dedicated native build environment with low turn around time. However, we would need to set up CI anyhow, so it might be a good first step to have a quick look at how things stack up in Travis:

https://docs.travis-ci.com/user/osx-ci-environment/

Of course, if we find that many adjustments are needed and turn around time is great, we shouldn't waste much human resources on this question until we have access to a dedicated build machine.

**Comment by ihrwein** [comment]
Travis also has some limits so if we push a lot of changes we will be banned.

**Comment by gregory094** [comment]
Hi,

I've started to port `3.8` to OS X. Here I list the issues I've collected during the development.

* [ ] __glibtool vs. libtool__: on Darwin based systems glibtool is used instead of libtool. We should handle this difference in `autogen.sh`. Both platforms respect the `LIBTOOL` variable so we should read the proper tool from that environmental variable.
* [ ] __bison__: the default `bison` version provided by *Apple Developer Tools* is `2.3` that doesn't support the `-W` option (`>=3.0`) that we use. That's why the user should install `bison 3.4` using `brew` and set the `YACC` environmental variable to `/usr/local/Cellular/bison/bin/bison` or use `brew link bison` in order to make it the default.
* [ ] __configure --with-java__: we use `find` while configuring java... that's bad. The `find` tool in *OSX* is little bit different from *UNIX-like-find*. It has a different interface and options.
* [ ] __configure --with-amqp__:  this is an _openssl_ related issue and not our fault. After `OSX 10.11 El Capitan` Apple removed `/usr/include/` that's why we get an error in configuration time. We should use `--with-opt-dir=/usr/local/Cellular/openssl/include` to avoid this.
* [ ] __ivykis_: I've already mentioned that `ivykis` has some problems dealing with *non-case-sensitive filesystems* because its structure contains files with the same name. We should patch `ivykis` or fork it and build *OS X* support with that. 

Next to this I've some propositions for the issues that @ihrwein collected that I'll comment to those issues.
After completing these problems I'm sure that we can have a working syslog-ng on *OS X* platforms and we can discuss about integrating to TravisCI.

**Comment by bkil-syslogng** [comment]
Thanks for the update. We are just in the process of optimizing our Travis
builds, so that would be a great addition to our portfolio.

**Comment by gregory094** [comment]
I've started to fix the issues, see PR #840.

**Comment by douglas-carmichael** [comment]
Any progress on these issues?

**Comment by bkil-syslogng** [comment]
@douglas-carmichael I can't speak for the other contributors, but a build platform is now being set up and we're making progress. I can't give any promises, but we're on track.

**Comment by lbudai** [comment]
Can we close this issue? Do we have a working syslog-ng on OS X?

**Comment by bkil-syslogng** [comment]
Some of the issues have been worked around/fixed in which we would need some insight from @MrAnno, @ngergo, @douglas-carmichael or some other OS X user:
https://github.com/balabit/syslog-ng/pull/1116
It also enables running `make check` on OS X, which is another step forward.

I would add a task for making `make func-test` and maybe `make distcheck` to run as well in Travis before making a definite statement.

**Comment by MrAnno** [comment]
I'm going to write a detailed description about the current status here.

In short:
We can compile and run syslog-ng on OS X 10.11 (El Capitan) with preinstalled dependencies (I used brew packages; unfortunately there are ["keg-only"](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/FAQ.md) deps as well).

t
- the system() source is currently not implemented
- modules are not tested
- one of our dependencies (ivykis) has some case-sensitivity issues (we should ask the maintainer to integrate and release [ivykis PR10](https://github.com/buytenh/ivykis/pull/10)).

**Comment by douglas-carmichael** [comment]
@MrAnno When I tried to compile 3.8.1 on OS X 10.11.6, I had several warnings (documented in issues #1174, #1175, #1176, #1177, and #1178 .)

What specific dependencies did you use?

**Comment by bkil-syslogng** [comment]
@douglas-carmichael Without doing a deeper investigation, I would say that these warnings are mostly harmless in respect of platform support. I can see similar warnings here. Please do report if you encounter any ill side effect with logging.

https://travis-ci.org/balabit/syslog-ng/jobs/161430348
https://s3.amazonaws.com/archive.travis-ci.org/jobs/161430348/log.txt

If you think you have a build issue, you can get an inspiration from `.travis.yml`. It is not as good as a container based reproduction environment, so you need to take it with a grain of salt. You can check version information in the build log.
https://github.com/balabit/syslog-ng/blob/78eae8ad5f9ff9e5f5fd1192aa246147acb96f6a/.travis.yml#L119

**Comment by douglas-carmichael** [comment]
When I try to build 3.9.1 on macOS 10.12.2, everything else builds fine but native-grammar.c fails:
```
  YACC   modules/native/native-grammar.c
  CC     modules/native/modules_native_libsyslog_ng_native_connector_a-native-grammar.o
clang: error: no such file or directory: './modules/native/native-grammar.c'
clang: error: no input files
Makefile:9490: recipe for target 'modules/native/modules_native_libsyslog_ng_native_connector_a-native-grammar.o' failed
gmake[2]: *** [modules/native/modules_native_libsyslog_ng_native_connector_a-native-grammar.o] Error 1
Makefile:14116: recipe for target 'all-recursive' failed
```

**Comment by bazsi** [comment]
That file is generated using bison. Maybe it has not been included in the
tarball for some reason or something removed it (make clean/distclean
perhaps).

It will be regenerated automatically if you install bison.

**Comment by dhm116** [comment]
I ran into the same issue as @douglas-carmichael with `3.9.1` on OSX `10.11.6`- I cloned the main repo and checked out the `syslog-ng-3.9.1` tag.

Configuration:
```
syslog-ng Open Source Edition 3.9.1 configured
 Compiler options:
  compiler                    : gcc
  compiler options            : -g -O2 -Wall -pthread  -D_REENTRANT -I/usr/local/Cellar/glib/2.50.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.50.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/eventlog/0.2.13/include/eventlog -I/usr/local/Cellar/pcre/8.39/include    -I$(top_srcdir)/lib/ivykis/src/include -I$(top_builddir)/lib/ivykis/src/include -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
  linker flags                : -L/usr/local/opt/bison/lib
  prefix                      : /usr/local
  linking mode                : dynamic
  embedded crypto             : no
  __thread keyword            : yes
 Test dependencies:
  Criterion                   : no
 Submodules:
  ivykis                      : internal
  mongoc                      : internal
  librabbitmq                 : no
  jsonc                       : internal
 Features:
  Debug symbols               : no
  GCC profiling               : no
  Memtrace                    : no
  IPV6 support                : yes
  spoof-source support        : no
  tcp-wrapper support         : no
  Linux capability support    : no
  Env wrapper support         : no
  systemd support             : no (unit dir: none)
  systemd-journal support     : no
  libmongo-client options     : yes
 Modules:
  Module search path          : ${exec_prefix}/lib/syslog-ng
  Sun STREAMS support (module): no
  SQL support (module)        : auto
  PACCT module (EXPERIMENTAL) : no
  MongoDB destination (module): no
  JSON support (module)       : yes
  SMTP support (module)       : no
  HTTP support (module)       : yes
  AMQP destination (module)   : no
  STOMP destination (module)  : no
  GEOIP support (module)      : no
  Redis support (module)      : no
  Riemann destination (module): no
  python                      : no (pkg-config package: python)
  java                        : yes
  java modules                : no
  native bindings             : auto
```

Make failure:
```
/Library/Developer/CommandLineTools/usr/bin/make --no-print-directory check-recursive
  YACC     modules/native/native-grammar.c
  CC       modules/native/modules_native_libsyslog_ng_native_connector_a-native-grammar.o
clang: error: no such file or directory: './modules/native/native-grammar.c'
clang: error: no input files
make[2]: *** [modules/native/modules_native_libsyslog_ng_native_connector_a-native-grammar.o] Error 1
make[1]: *** [check-recursive] Error 1
make: *** [check] Error 2
```

I have bison 3 via homebrew:
```
==> Downloading https://homebrew.bintray.com/bottles/bison-3.0.4.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring bison-3.0.4.el_capitan.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Some formulae require a newer version of bison.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/bison/lib

==> Summary
🍺  /usr/local/Cellar/bison/3.0.4: 51 files, 2.1M
```

**Comment by douglas-carmichael** [comment]
I was able to successfully get 3.13.2 to compile on OS X 10.13.3 until linking lib/libsyslog-ng.la:
```



CCLD     lib/libsyslog-ng.la
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
ld: warning: option -noall_load is obsolete and being ignored
ld: warning: option -noall_load is obsolete and being ignored
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-apphook.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-cfg.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-cfg-lexer.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-cfg-lexer-subst.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-cfg-parser.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-logreader.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-logqueue-fifo.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-logthrdestdrv.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-logwriter.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-mainloop-call.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-mainloop.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-mainloop-worker.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-mainloop-io-worker.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-ml-batched-timer.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-msg-format.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-plugin.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-cfg-lex.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/.libs/lib_libsyslog_ng_la-cfg-grammar.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/logproto/.libs/lib_libsyslog_ng_la-logproto-client.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/logproto/.libs/lib_libsyslog_ng_la-logproto-server.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/logproto/.libs/lib_libsyslog_ng_la-logproto-builtins.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/filter/.libs/lib_libsyslog_ng_la-filter-expr-grammar.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/parser/.libs/lib_libsyslog_ng_la-parser-expr-grammar.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/rewrite/.libs/lib_libsyslog_ng_la-rewrite-expr-grammar.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/template/.libs/lib_libsyslog_ng_la-templates.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/template/.libs/lib_libsyslog_ng_la-simple-function.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/template/.libs/lib_libsyslog_ng_la-repr.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/template/.libs/lib_libsyslog_ng_la-user-function.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/template/.libs/lib_libsyslog_ng_la-compiler.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/stats/.libs/lib_libsyslog_ng_la-stats-control.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/control/.libs/lib_libsyslog_ng_la-control-commands.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/control/.libs/lib_libsyslog_ng_la-control-main.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/debugger/.libs/lib_libsyslog_ng_la-debugger.o
duplicate symbol _main_loop_workers_running in:
    lib/.libs/lib_libsyslog_ng_la-afinter.o
    lib/debugger/.libs/lib_libsyslog_ng_la-debugger-main.o
ld: 34 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libsyslog-ng.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

[DC_syslog-ng-3.13.2_osx.log](https://github.com/balabit/syslog-ng/files/1731980/DC_syslog-ng-3.13.2_osx.log)
[DC_syslog-ng-3.13.2_osx_config.log](https://github.com/balabit/syslog-ng/files/1731981/DC_syslog-ng-3.13.2_osx_config.log)

**Comment by furiel** [comment]
@douglas-carmichael this issue is recently fixed in https://github.com/balabit/syslog-ng/pull/1862.
Please try out the github master for now. This patch will be part of the next release: 3.14

**Comment by Kokan** [comment]
Thanks to @MrAnno  syslog-ng compiles on OSX, and there is a travis job, to keep it that way.

**Comment by MrAnno** [comment]
Updated macOS compilation guide:
https://syslog-ng.gitbooks.io/getting-started/content/chapters/chapter_0/section_3.html
