### PR TITLE
Add "curl" module

### PR DESCRIPTION
**Pull request by falzm**

### CODE REVIEW

**Comment by lbudai** [comment]
Hi, 

here is the error msg:

```
modules/curl/curl-plugin.c:28:8: error: unknown type name 'Plugin'
static Plugin curl_plugins[] =
       ^
modules/curl/curl-plugin.c:40:3: error: implicit declaration of function
      'plugin_register' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  plugin_register(cfg, curl_plugins, G_N_ELEMENTS(curl_plugins));
  ^
  CC     modules/dbparser/modules_dbparser_libdbparser_la-pdb-load.lo
modules/curl/curl-plugin.c:44:7: error: unknown type name 'ModuleInfo'
const ModuleInfo module_info =
      ^
3 errors generated.
  CC     modules/dbparser/modules_dbparser_libdbparser_la-pdb-rule.lo
make[2]: *** [modules/curl/modules_curl_libcurl_la-curl-plugin.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
curl-grammar.y:780:13: error: use of undeclared identifier 'Plugin'
            Plugin *p;
            ^
curl-grammar.y:780:21: error: use of undeclared identifier 'p'
            Plugin *p;
                    ^
curl-grammar.y:784:13: error: use of undeclared identifier 'p'
            p = plugin_find(configuration, context, (yyvsp[(1) - (1)].cptr));
            ^
curl-grammar.y:784:17: error: implicit declaration of function 'plugin_find' is
      invalid in C99 [-Werror,-Wimplicit-function-declaration]
            p = plugin_find(configuration, context, (yyvsp[(1) - (1)].cptr));
                ^
curl-grammar.y:785:25: error: use of undeclared identifier 'p'
            CHECK_ERROR(p, (yylsp[(1) - (1)]), "%s plugin %s not found"...
                        ^
curl-grammar.y:97:11: note: expanded from macro 'CHECK_ERROR'
    if (!(val))                                                         \
          ^
curl-grammar.y:787:21: error: implicit declaration of function
      'plugin_parse_config' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
            value = plugin_parse_config(p, configuration, &(yylsp[(1) - ...
                    ^
curl-grammar.y:787:41: error: use of undeclared identifier 'p'
            value = plugin_parse_config(p, configuration, &(yylsp[(1) - ...
                                        ^
7 errors generated.
```

**Comment by falzm** [comment]
Hmm, have I missed something? I didn't have those errors when compiling locally :(

**Comment by czanik** [comment]
Just a guess (did not check, but have seen similar problems before): you developed / tested using syslog-ng 3.7 while we work on 3.8...

**Comment by falzm** [comment]
@czanik I branched from the master branch at the time, version reported was `3.8.0alpha0`.

**Comment by falzm** [comment]
Wow, sorry I must have did something wrong with my git branch... I'll cancel this PR and sync my branch from the current master then make a new PR.
