### ISSUE TITLE
3.7 alpha1 does not compile on earlier FreeBSD releases

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#317]
syslog-ng 3.7 alpha1 compiles fine on FreeBSD 10.1 (the latest release), but fails to compile on earlier releases. Originally reported by Cy (FreeBSD ports maintainer) on FreeBSD 8.4 and 9.1. Reproduced here on FreeBSD 9.2:

root@fb92:/usr/ports/sysutils/syslog-ng-devel # make
===>  Building for syslog-ng-devel-3.7.0a1
gmake --no-print-directory all-recursive
  CC       lib/lib_libsyslog_ng_la-logmsg.lo
In file included from lib/logmsg.c:37:
lib/template/macros.h:30: error: redefinition of typedef 'LogTemplateOptions'
lib/template/templates.h:89: error: previous declaration of 'LogTemplateOptions' was here
Makefile:6851: recipe for target 'lib/lib_libsyslog_ng_la-logmsg.lo' failed
gmake[2]: *** [lib/lib_libsyslog_ng_la-logmsg.lo] Error 1
Makefile:9939: recipe for target 'all-recursive' failed
gmake[1]: *** [all-recursive] Error 1
Makefile:4068: recipe for target 'all' failed
gmake: *** [all] Error 2
*** [do-build] Error code 1

Stop in /usr/ports/sysutils/syslog-ng-devel.
*** [stage] Error code 1

Stop in /usr/ports/sysutils/syslog-ng-devel.
root@fb92:/usr/ports/sysutils/syslog-ng-devel #

**Comment by ihrwein** [comment]
@czanik could you test it? I would like to close the old pending issues.

**Comment by czanik** [comment]
syslog-ng 3.6 compiles fine on the same platforms. I was suggested, that tweeking compiler parameters will most likely fix the issue. If so, please set that automagically by configure!

**Comment by czanik** [comment]
SLES 11 is also affected:

[  180s]   CC     lib/rewrite/lib_libsyslog_ng_la-rewrite-expr-grammar.lo
[  181s]   CC     lib/rewrite/lib_libsyslog_ng_la-rewrite-groupset.lo
[  181s]   CC     lib/template/lib_libsyslog_ng_la-templates.lo
[  181s] In file included from ./lib/template/repr.h:28,
[  181s]                  from lib/template/templates.c:25:
[  181s] ./lib/template/function.h:31: error: redefinition of typedef 'LogTemplateOptions'
[  181s] ./lib/template/common-template-typedefs.h:27: error: previous declaration of 'LogTemplateOptions' was here
[  181s] ./lib/template/function.h:32: error: redefinition of typedef 'LogTemplate'
[  181s] ./lib/template/templates.h:70: error: previous declaration of 'LogTemplate' was here
[  181s] In file included from lib/template/templates.c:26:
[  181s] ./lib/template/compiler.h:30: error: redefinition of typedef 'LogTemplate'
[  181s] ./lib/template/function.h:32: error: previous declaration of 'LogTemplate' was here
[  181s] make[2]: *** [lib/template/lib_libsyslog_ng_la-templates.lo] Error 1
[  181s] make[1]: *** [all-recursive] Error 1
[  181s] make: *** [all] Error 2
[  181s] error: Bad exit status from /var/tmp/rpm-tmp.50624 (%build)

SLES 11 GCC version:
linux-3f8h:~> gcc -v
Using built-in specs.
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.3 --enable-ssp --disable-libssp --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --program-suffix=-4.3 --enable-linux-futex --without-system-libunwind --with-cpu=generic --build=x86_64-suse-linux
Thread model: posix
gcc version 4.3.4 [gcc-4_3-branch revision 152973] (SUSE Linux) 
linux-3f8h:~> 

FreeBSD 9.3 GCC version:
root@fb92:~ # gcc -v
Using built-in specs.
Target: amd64-undermydesk-freebsd
Configured with: FreeBSD/amd64 system compiler
Thread model: posix
gcc version 4.2.1 20070831 patched [FreeBSD]

**Comment by czanik** [comment]
And RHEL 6 is also affected:

  CC     lib/rewrite/lib_libsyslog_ng_la-rewrite-groupset.lo
  CC     lib/template/lib_libsyslog_ng_la-templates.lo
In file included from ./lib/template/repr.h:29,
                 from lib/template/templates.c:26:
./lib/template/function.h:31: error: redefinition of typedef 'LogTemplateOptions'
./lib/template/common-template-typedefs.h:27: note: previous declaration of 'LogTemplateOptions' was here
./lib/template/function.h:32: error: redefinition of typedef 'LogTemplate'
./lib/template/templates.h:70: note: previous declaration of 'LogTemplate' was here
In file included from lib/template/templates.c:27:
./lib/template/compiler.h:30: error: redefinition of typedef 'LogTemplate'
./lib/template/function.h:32: note: previous declaration of 'LogTemplate' was here
make[2]: *** [lib/template/lib_libsyslog_ng_la-templates.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

GCC version info:
[root@localhost ~]# chroot /var/lib/mock/epel-6-x86_64/root/
bash-4.1# gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

**Comment by bazsi** [comment]
Is this still alpha1 or the latest master? We did commit a fix past alpha1.

Pls attach the exact git commit.

Thanks

**Comment by czanik** [comment]
Today's tests were done on 3.7.0beta1 release tgz.

**Comment by bazsi** [comment]
Hi,

Can you pls provide access to a freebsd image where this occurs? maybe
login to your env when you are in the office?
thanks


-- 
Bazsi

**Comment by czanik** [comment]
I can upload it somewhere when I'm next in the office. But you don't need FreeBSD: it fails with any slightly older GCC, so also on RHEL6, SLES11

**Comment by bazsi** [comment]
I dont have either of those.

**Comment by ihrwein** [comment]
I was able to build the latest master on CentOs 6.6 in a Docker container with some fixes.

@czanik Could you test my branch (although I didn't touch LogTemplateOptions...)? 

https://github.com/ihrwein/syslog-ng/tree/f/fix-centos6-build

It's not ready to merge, we should set the proper bison parameters on every OS.

**Comment by czanik** [comment]
This problem was fixed by @bazsi in
https://github.com/balabit/syslog-ng/pull/466 and I verified it on FreeBSD
9.3 and SLES11

Peter Czanik (CzP) <peter.czanik@balabit.com>
BalaBit IT Security / syslog-ng upstream
http://czanik.blogs.balabit.com/
https://twitter.com/PCzanik

**Comment by ihrwein** [comment]
Then pls, close this issue.

**Comment by czanik** [comment]
fixed by https://github.com/balabit/syslog-ng/pull/466
