### ISSUE TITLE
./lib/.libs/libsyslog-ng.so: undefined reference to `sd_notify'

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#515]
Compiling with systemd support fails on openSUSE 13.1, which has systemd version 208:
```
[   73s]   CCLD   modules/dbparser/libsyslog-ng-patterndb.la
[   73s]   CCLD   lib/tests/test_host_resolve
[   73s]   GEN    syslog-ng/syslog-ng
[   73s] ./lib/.libs/libsyslog-ng.so: undefined reference to `sd_notify'
[   73s] collect2: error: ld returned 1 exit status
[   73s] make[2]: *** [lib/tests/test_host_resolve] Error 1
[   73s] make[2]: *** Waiting for unfinished jobs....
[   73s] /home/abuild/rpmbuild/BUILD/syslog-ng-3.6.3/lib/.libs/libsyslog-ng.so: undefined reference to `sd_notify'
[   73s] collect2: error: ld returned 1 exit status
[   73s] make[2]: *** [syslog-ng/syslog-ng] Error 1
[   73s] make[1]: *** [all-recursive] Error 1
[   73s] make: *** [all] Error 2
```
It compiles fine on openSUSE 13.2, which has sytemd version 210.

**Comment by czanik** [comment]
All systemd related packages are installed in the build chroot, so it's most likely not a missing dependency. Related changelog entry:
```
Monolithic libsystemd library support added.
In systemd 209, the various small libsystemd-* libraries were merged
into a single libsystemd. From now, syslog-ng detects and
uses the merged library when present, while still supports the split
ones too. If the merged library is found, that will be preferred.
```

**Comment by ihrwein** [comment]
Is the `systemd-devel` package installed?

**Comment by czanik** [comment]
Yes, it is:
```
linux-3f8h:~> rpm -qi systemd-devel
Name        : systemd-devel
Version     : 208
Release     : 6.1
Architecture: x86_64
Install Date: Tue Jun  9 07:05:29 2015
Group       : Development/Libraries/C and C++
Size        : 43384
License     : LGPL-2.1+
Signature   : RSA/SHA256, Thu Oct 24 13:27:05 2013, Key ID b88b2fd43dbdc284
Source RPM  : systemd-208-6.1.src.rpm
Build Date  : Thu Oct 24 13:24:57 2013
Build Host  : build13
Relocations : (not relocatable)
Packager    : http://bugs.opensuse.org
Vendor      : openSUSE
URL         : http://www.freedesktop.org/wiki/Software/systemd
Summary     : Development headers for systemd
Description :
Development headers and auxiliary files for developing applications for systemd.
Distribution: openSUSE 13.1
```

**Comment by ihrwein** [comment]
Please try the following workaround:

In `configure.ac` at the 35th line you can see this: 

```
LIBSYSTEMD_MIN_VERSION="209"
```

Change `209` to `208`, run `autoconf`, then `configure` with your usual parameters. Does this work?

**Comment by ihrwein** [comment]
Could you paste here the build dependencies of syslog-ng on OpenSuse?

**Comment by lbudai** [comment]
for my test Debian builds, I'm using the following build dependencies:
* dh-systemd (>= 1.3), [of cource, you won't have this one :-) ]
* libsystemd-daemon-dev,
* libsystemd-journal-dev (>= 195)

**Comment by czanik** [comment]
Did the change, but received the same error.
Spec file with dependencies is accessible at https://build.opensuse.org/package/view_file/home:czanik:syslog-ng36/syslog-ng/syslog-ng.spec?expand=1 and contains systemd-devel. There are no other related devel files (except for systemd-mini-devel used during bootstraping the distro, which conflicts with systemd-devel).

**Comment by lbudai** [comment]
I checked it on Ubuntu 14.04 and 14.10 : got the same error.
(works only on Ubuntu 15.04 and Debian 8)

**Comment by lbudai** [comment]
I've just check the code again and found what is the problem, in configure.ac:
```
 libsystemd_CFLAGS="${LIBSYSTEMD_JOURNAL_CFLAGS} ${libsystemd_daemon_CFLAGS}"
 libsystemd_LDFLAGS="${LIBSYSTEMD_JOURNAL_LIBS} ${libsystemd_daemon_LIBS}"
 AC_SUBST(libsystemd_CFLAGS)
 AC_SUBST(libsystemd_LIBS)
```
Here, we should set `libsystemd_LIBS`  instead of `libsystemd_LDFLAGS`.
If you don't want to re-generate configure, just find `libsystemd_LDFLAGS` in configure and replace it to `libsystemd_LIBS` (line 16354).

**Comment by ihrwein** [comment]
#516 was merged, so this issue should be solved. @czanik would you close it?

**Comment by czanik** [comment]
Just did a quick test with a self generated release tgz on openSUSE 13.1 and SLES 12, and both fail with the following message:

```
[   43s] Making all in kojines
[   43s] gcc -DHAVE_CONFIG_H -I. -I../..  -I../../src/include -I../../src/include   -fmessage-length=0 -grecord-gcc-switches -fstack-protector -O2 -Wall -D_FORTIFY_SOURCE=2 -funwind-tables -fasynchronous-unwind-tables -Wall -pthread -c main.c
[   43s] gcc -DHAVE_CONFIG_H -I. -I../..  -I../../src/include -I../../src/include   -fmessage-length=0 -grecord-gcc-switches -fstack-protector -O2 -Wall -D_FORTIFY_SOURCE=2 -funwind-tables -fasynchronous-unwind-tables -Wall -pthread -c kojines.c
[   43s] /bin/sh ../../libtool  --tag=CC   --mode=link gcc  -fmessage-length=0 -grecord-gcc-switches -fstack-protector -O2 -Wall -D_FORTIFY_SOURCE=2 -funwind-tables -fasynchronous-unwind-tables -Wall -pthread   -o kojines main.o kojines.o ../../src/libivykis.la 
[   43s] libtool: link: gcc -fmessage-length=0 -grecord-gcc-switches -fstack-protector -O2 -Wall -D_FORTIFY_SOURCE=2 -funwind-tables -fasynchronous-unwind-tables -Wall -pthread -o kojines main.o kojines.o  ../../src/.libs/libivykis.a -pthread
[   43s] make[6]: Nothing to be done for 'all-am'.
[   43s] Making all in misc
[   43s] make[5]: Nothing to be done for 'all'.
[   43s] Making all in man3
[   43s] make[5]: Nothing to be done for 'all'.
[   43s] Makefile:9861: recipe for target 'all-recursive' failed
[   43s] make[1]: *** [all-recursive] Error 1
[   43s] Makefile:4057: recipe for target 'all' failed
[   43s] make: *** [all] Error 2
[   43s] error: Bad exit status from /var/tmp/rpm-tmp.OZyfi5 (%build)
```

**Comment by lbudai** [comment]
hi,

this is how I generate the dist tarball:

```shell
git clone https://github.com/balabit/syslog-ng                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                      
cd syslog-ng                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                      
git checkout 3.6/master                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                      
./autogen.sh                                                                                                                                                                                                                                                          

./configure \
 --with-ivykis=internal \
 --with-libmongo-client=internal \
 --enable-all-modules \
 --disable-sun-streams \
 --enable-shared \
 --enable-dynamic-linking \
 --enable-manpages

make

make dist
make distcheck
```

**Comment by lbudai** [comment]
and here are my configure options when building Debian packages:
```
	dh_auto_configure -- \
		--build=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE) \
		--prefix=/usr \
		--mandir=/usr/share/man \
		--sysconfdir=/etc/syslog-ng \
		--localstatedir=/var/lib/syslog-ng \
		--datadir=/usr/share/syslog-ng \
		--libdir=/usr/lib/syslog-ng \
		--disable-silent-rules \
		\
                --enable-manpages \
		--enable-dynamic-linking \
		--enable-ssl \
		--enable-spoof-source \
		--enable-tcp-wrapper \
		--enable-sql \
		--enable-mongodb \
		--enable-json \
		--enable-riemann \
		\
		--with-libmongo-client=system \
		--with-ivykis=system \
		\
		--with-module-dir='$${exec_prefix}/lib/syslog-ng/${UMAJOR}' \
		--with-systemdsystemunitdir="/lib/systemd/system" \
		\
		SOURCE_REVISION="$${SOURCE_REVISION}" \
		${SYSTEMD_CONFIGURE_OPTS} \
		${EXTRA_CONFIGURE_OPTS}
```

**Comment by czanik** [comment]
OK, problem resolved: "./configure" before "make dist" needs the "--enable-manpages" option. If it's there, the fix compiles on all of my tested platforms.
