### ISSUE TITLE
git head does not compile on many platforms

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#1403]
# syslog-ng

## Version of syslog-ng

git head (31849565a24b034618df8230aa72ea3c85ffb619)

## Platform

Fedora 25

# Issue

## Failure

Compilation fails:

```
  GEN      modules/java/org_syslog_ng_InternalMessageSender.h
make --no-print-directory all-recursive
  CC       modules/native/modules_native_libsyslog_ng_native_connector_a-native-grammar.o
In file included from /usr/include/bits/libc-header-start.h:33:0,
                 from /usr/include/limits.h:26,
                 from /usr/lib/gcc/x86_64-redhat-linux/7/include/limits.h:194,
                 from /usr/lib/gcc/x86_64-redhat-linux/7/include/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-redhat-linux/7/include/limits.h:34,
                 from /usr/lib64/glib-2.0/include/glibconfig.h:11,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from ./lib/compat/glib.h:30,
                 from ./lib/syslog-ng.h:35,
                 from ./lib/cfg-parser.h:28,
                 from modules/native/native-parser.h:28,
                 from modules/native/native-grammar.y:26:
/usr/include/features.h:181:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:9326: modules/native/modules_native_libsyslog_ng_native_connector_a-native-grammar.o] Error 1
make[1]: *** [Makefile:14106: all-recursive] Error 1
make: *** [Makefile:5752: all] Error 2
```

## Steps to reproduce

Compile syslog-ng git head on Fedora

My suspicion is: https://github.com/balabit/syslog-ng/commit/31849565a24b034618df8230aa72ea3c85ffb619 where: "-Werror" was added.

**Comment by czanik** [comment]
Originally discovered on Fedora, it seems that openSUSE / SLES is also heavily affected. If you take a look at https://build.opensuse.org/project/show/home:czanik:syslog-ng-githead you can see, that too old (SLES 11) and too new (Tumbleweed) do not compile either:
```
[   67s]   CC       lib/stats/lib_libsyslog_ng_la-stats-query.lo
[   67s] cc1: warnings being treated as errors
[   67s] lib/stats/stats-query.c: In function '_stats_query_get':
[   67s] lib/stats/stats-query.c:201: error: implicit declaration of function 'g_list_free_full'
[   67s] make[2]: *** [lib/stats/lib_libsyslog_ng_la-stats-query.lo] Error 1
[   67s] make[1]: *** [all-recursive] Error 1
[   67s] make: *** [all] Error 2
```

**Comment by presidento** [comment]
@czanik can you test it again?

**Comment by czanik** [comment]
@presidento : Done. It compiles again on Tumbleweed, but still fails on SLES 11:
```
[   91s]   CCLD     modules/dbparser/libsyslog-ng-patterndb.la
[   91s]   CC       modules/dbparser/pdbtool/modules_dbparser_pdbtool_pdbtool-pdbtool.o
[   91s]   CCLD     modules/dbparser/pdbtool/pdbtool
[   91s] ./lib/.libs/libsyslog-ng.so: undefined reference to `g_list_free_full'
[   91s] collect2: ld returned 1 exit status
[   91s] make[2]: *** [modules/dbparser/pdbtool/pdbtool] Error 1
[   91s] make[1]: *** [all-recursive] Error 1
[   91s] make: *** [all] Error 2
```
On the other hand it seems to be something new and unrelated, most likely introduced in one of the recent other commits.

**Comment by MrAnno** [comment]
Yeah, `g_list_free_full()` is only available from glib v2.28.
This has been introduced in d9c3d25b.

**Comment by czanik** [comment]
It will affect RHEL 6 (has the same glib version as SLES 11) and most likely also some of the older Debian and Ubuntu releases.

**Comment by kvch** [comment]
It is weird because `g_list_free_full` is used in several modules, e. g. `http` or `afmongodb`. @czanik don't you build those modules, too?

**Comment by czanik** [comment]
I don't build it on SLES11, which has glib v2.22

I build it on RHEL6. Just checked, they updated to v2.28 recently. At least now I understand why some features do not work on earlier RHEL6 releases...

**Comment by czanik** [comment]
Just tested RHEL 6. If tails with:
```
  CCLD     modules/dbparser/pdbtool/pdbtool
./lib/.libs/libsyslog-ng.so: undefined reference to `g_atomic_pointer_add'
collect2: ld returned 1 exit status
make[2]: *** [modules/dbparser/pdbtool/pdbtool] Error 1
make[1]: *** [all-recursive] Error 1
```

**Comment by faxm0dem** [comment]
we still use RHEL6 in production, so thanks for looking into this!

**Comment by bazsi** [comment]
Hi,

Albeit we can work around these kind of issues for some time yet, it's not
going to be easy down the line and is going to be more and more difficult.

Reverting that change might cost us the *64 bit statistics *counters, which
means we would be using 32 bits only. At 100k/sec, this would overflow in
roughly 4 days. If we are using byte counters (which we also introduced),
those would overflow in 40-50 *seconds. *Not very useful.

So obviously, we can workaround this one, especially if you are not yet
using the new counters, but not for all eternity. It might be an option to
have an updated glib package for EPEL6, but again, glib being a pretty
important system library is not easy.

Bundling would work (e.g. syslog-ng binaries to include glib, separate from
the system's version), but that's the kind of work Balabit does in its
Premium Editions and I personally wouldn't want to undertake that as a part
of the open source project, at least not without active volunteers doing
the work. The agility of the open source version comes from the fact that
we don't need to do the costly maintenance of binaries.

With that said, please plan on migrating to newer versions of the OS, if
you plan to deploy bleeding edge syslog-ng binaries. Or consider things
like a chroot/docker, or manually built binaries, using glib in /usr/local.

Cheers,
Bazsi


-- 
Bazsi

**Comment by bazsi** [comment]
can you check if this branch makes things compile on centos6?

https://github.com/balabit/syslog-ng/pull/1837

@czanik @faxm0dem
