### PR TITLE
Fix python module compilation with python3.4

### LINKED ISSUE #674: Compile error related to python module
I am trying to compile 3.7.1. When I use the configure flag --with-python=3.4 i get the following errors
```
  CCLD   modules/systemd-journal/libsdjournal.la
  CC     modules/python/modules_python_libmod_python_la-python-config.lo
  CC     modules/python/modules_python_libmod_python_la-python-helpers.lo
modules/python/python-helpers.c: In function '_py_get_callable_name':
modules/python/python-helpers.c:34:7: warning: implicit declaration of function 'PyString_AsString' [-Wimplicit-function-declaration]
       g_strlcpy(buf, PyString_AsString(name), buf_len);
       ^
modules/python/python-helpers.c:34:7: warning: passing argument 2 of 'g_strlcpy' makes pointer from integer without a cast [enabled by default]
In file included from /usr/include/glib-2.0/glib.h:79:0,
                 from ./lib/compat/glib.h:30,
                 from ./lib/syslog-ng.h:35,
                 from modules/python/python-module.h:27,
                 from modules/python/python-helpers.h:27,
                 from modules/python/python-helpers.c:24:
/usr/include/glib-2.0/glib/gstrfuncs.h:117:21: note: expected 'const gchar *' but argument is of type 'int'
 gsize               g_strlcpy        (gchar      *dest,
                     ^
modules/python/python-helpers.c: In function '_py_format_exception_text':
modules/python/python-helpers.c:61:7: warning: format '%s' expects argument of type 'char *', but argument 5 has type 'int' [-Wformat=]
       g_snprintf(buf, buf_len, "%s: %s", ((PyTypeObject *) exc)->tp_name, PyString_AsString(str));
       ^
  CC     modules/python/modules_python_libmod_python_la-python-main.lo
  CC     modules/python/modules_python_libmod_python_la-python-plugin.lo
  CC     modules/python/modules_python_libmod_python_la-python-grammar.lo
  CC     modules/python/modules_python_libmod_python_la-python-value-pairs.lo
  CC     modules/python/modules_python_libmod_python_la-python-dest.lo
modules/python/python-dest.c: In function 'python_dd_insert_to_dict':
modules/python/python-dest.c:99:3: warning: implicit declaration of function 'PyString_FromStringAndSize' [-Wimplicit-function-declaration]
   PyObject *key_pyobj = PyString_FromStringAndSize((gchar*) key, strlen((gchar*) key));
   ^
modules/python/python-dest.c:99:25: warning: initialization makes pointer from integer without a cast [enabled by default]
   PyObject *key_pyobj = PyString_FromStringAndSize((gchar*) key, strlen((gchar*) key));
                         ^
modules/python/python-dest.c:100:27: warning: initialization makes pointer from integer without a cast [enabled by default]
   PyObject *value_pyobj = PyString_FromStringAndSize((gchar*) value, strlen((gchar*) value));
                           ^
  CC     modules/python/modules_python_libmod_python_la-python-tf.lo
modules/python/python-tf.c: In function '_py_construct_args_tuple':
modules/python/python-tf.c:42:7: warning: implicit declaration of function 'PyString_FromString' [-Wimplicit-function-declaration]
       PyTuple_SetItem(args, i, PyString_FromString(argv[i]->str));
       ^
modules/python/python-tf.c:42:7: warning: passing argument 3 of 'PyTuple_SetItem' makes pointer from integer without a cast [enabled by default]
In file included from /usr/include/python3.4m/Python.h:85:0,
                 from modules/python/python-module.h:28,
                 from modules/python/python-tf.c:25:
/usr/include/python3.4m/tupleobject.h:46:17: note: expected 'struct PyObject *' but argument is of type 'int'
 PyAPI_FUNC(int) PyTuple_SetItem(PyObject *, Py_ssize_t, PyObject *);
                 ^
modules/python/python-tf.c: In function '_py_convert_return_value_to_result':
modules/python/python-tf.c:84:3: warning: implicit declaration of function 'PyString_Check' [-Wimplicit-function-declaration]
   if (!PyString_Check(ret))
   ^
modules/python/python-tf.c:93:3: warning: implicit declaration of function 'PyString_AS_STRING' [-Wimplicit-function-declaration]
   g_string_append(result, PyString_AS_STRING(ret));
   ^
modules/python/python-tf.c:93:3: warning: passing argument 2 of 'g_string_append' makes pointer from integer without a cast [enabled by default]
In file included from /usr/include/glib-2.0/glib/giochannel.h:34:0,
                 from /usr/include/glib-2.0/glib.h:54,
                 from ./lib/compat/glib.h:30,
                 from ./lib/syslog-ng.h:35,
                 from ./lib/template/function.h:28,
                 from modules/python/python-tf.h:27,
                 from modules/python/python-tf.c:24:
/usr/include/glib-2.0/glib/gstring.h:80:14: note: expected 'const gchar *' but argument is of type 'int'
 GString*     g_string_append            (GString         *string,
              ^
  CC     modules/python/modules_python_libmod_python_la-python-parser.lo
  CC     modules/python/modules_python_libmod_python_la-python-logmsg.lo
modules/python/python-logmsg.c: In function 'py_log_message_getattr':
modules/python/python-logmsg.c:48:3: warning: implicit declaration of function 'PyString_FromString' [-Wimplicit-function-declaration]
   return PyString_FromString(value);
   ^
modules/python/python-logmsg.c:48:3: warning: return makes pointer from integer without a cast [enabled by default]
modules/python/python-logmsg.c: At top level:
modules/python/python-logmsg.c:73:3: warning: missing braces around initializer [-Wmissing-braces]
   PyObject_HEAD_INIT(&PyType_Type)
   ^
modules/python/python-logmsg.c:73:3: warning: (near initialization for 'py_log_message_type.ob_base.ob_base') [-Wmissing-braces]
modules/python/python-logmsg.c:75:3: error: unknown field 'ob_size' specified in initializer
   .ob_size = 0,
   ^
modules/python/python-logmsg.c:83:3: error: unknown field 'tp_compare' specified in initializer
   .tp_compare = NULL,
   ^
make[2]: *** [modules/python/modules_python_libmod_python_la-python-logmsg.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
mike@UbuntuWorkstation:~/syslog-ng-3.7.1$
```
If I compile with --with-python=2.7 it compiles fine.

### PR DESCRIPTION
**Pull request by dnsjts**
The first part of this pull request consists trivial changes, the second part tries to fix the initialization of the python-debugger (yet to be commited).

Fixes #674.

### CODE REVIEW

**Comment by bazsi** [comment]
Is it going to work with python2 as well as python3?

**Comment by dnsjts** [comment]
The first five change should work with python2 without problem, and the python-debugger will contain some ugly ` #if PY_MAJOR_VERSION >= 3` checks in order to work with both python2 and python3.

**Comment by lbudai** [comment]
@u2yg , @dnsjts : could you setup one or two PR based on this PR and #730, #731, #732 ?

**Comment by dnsjts** [comment]
@lbudai The PR has been reduced, please review it.
