### PR TITLE
Properly declare main_loop_workers_running extern

### PR DESCRIPTION
**Pull request by opoplawski**
This resolves the following build error on OSX 10.13:
```
:info:build   CCLD     lib/libsyslog-ng.la
:info:build clang: warning: argument unused during compilation: '-pthread'
:info:build clang: warning: argument unused during compilation: '-pthread'
:info:build ld: warning: option -noall_load is obsolete and being ignored
:info:build ld: warning: option -noall_load is obsolete and being ignored
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-apphook.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-cfg.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-cfg-lexer.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-cfg-lexer-subst.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-cfg-parser.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-logqueue-fifo.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-logreader.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-logthrdestdrv.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-logwriter.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-mainloop.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-mainloop-call.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-mainloop-worker.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-mainloop-io-worker.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-ml-batched-timer.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-msg-format.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-plugin.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-cfg-lex.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-cfg-grammar.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/logproto/.libs/lib_libsyslog_ng_la-logproto-client.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/logproto/.libs/lib_libsyslog_ng_la-logproto-server.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/logproto/.libs/lib_libsyslog_ng_la-logproto-builtins.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/filter/.libs/lib_libsyslog_ng_la-filter-expr-grammar.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/parser/.libs/lib_libsyslog_ng_la-parser-expr-grammar.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/rewrite/.libs/lib_libsyslog_ng_la-rewrite-expr-grammar.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/template/.libs/lib_libsyslog_ng_la-templates.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/template/.libs/lib_libsyslog_ng_la-simple-function.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/template/.libs/lib_libsyslog_ng_la-repr.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/template/.libs/lib_libsyslog_ng_la-compiler.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/template/.libs/lib_libsyslog_ng_la-user-function.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/stats/.libs/lib_libsyslog_ng_la-stats-control.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/control/.libs/lib_libsyslog_ng_la-control-commands.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/control/.libs/lib_libsyslog_ng_la-control-main.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/debugger/.libs/lib_libsyslog_ng_la-debugger.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/debugger/.libs/lib_libsyslog_ng_la-debugger-main.o
:info:build ld: 34 duplicate symbols for architecture x86_64
:info:build clang: error: linker command failed with exit code 1 (use -v to see invocation)
:info:build make[2]: *** [lib/libsyslog-ng.la] Error 1
:info:build make[1]: *** [all-recursive] Error 1
:info:build make: *** [all] Error 2
```

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by opoplawski** [comment]
Or are these just stragglers from the main_loop_workers_running -> main_loop_jobs_running rename in commit a463301eb88e72b938a48a27fc7a11318bea313b ?

**Comment by furiel** [comment]
Thank you for reporting. This regression was introduced in https://github.com/balabit/syslog-ng/pull/1666/commits/33c999d3254544bf31136e5677d47e0b53952e11. The renaming was intentional. The original variable calculated the running jobs at that time, which is not necesseraliy equals to the number of running workers due workers have a 10s timeout after a job. And in that specific I fix needed to run a little code that depends on the number of workers, hence the rename, and a (new) variable introduced in with the original name.

This issue is currently being addressed in #1302 in this specific patch: https://github.com/balabit/syslog-ng/pull/1302/commits/35acef621ce44ec7e7973ab21b3070c8834de61f: Moved main_loop_workers_running declaration from .h to .c

**Comment by lbudai** [comment]
@furiel
@szemere: what is your plan? merge this PR, or, merge #1302(as this fix is part of that PR)?

**Comment by szemere** [comment]
Hello,
 thank you for asking. I think enable-warnings has other issues right now, so I don't want to block this PR, I will rebase #1302 later.

OK to go.

**Comment by lbudai** [comment]
Thanks!
